### PR TITLE
Feature/slave response

### PR DESCRIPTION
**Pull request by haggl**
Fixes some docstring typos and adds missing bindings for `py_aa_i2c_slave_set_response` and `py_aa_i2c_slave_write_stats`.

### CODE REVIEW

**Comment by haggl** [comment]
I can refactor the API to provide properties instead of functions if you wish.

I have another branch in store which adds GPIO functionality. I used properties for that as well.

On June 29, 2017 9:34:08 AM GMT+02:00, Michael Walle <notifications@github.com> wrote:
>mwalle requested changes on this pull request.
>
>Please fix the docstring and provide test cases for both functions.
>
>And after looking a second time at this patch, I'm not sure if we
>should use properties for "enable/disable_i2c_slave()",
>"i2c_slave_set_response()" and "i2c_slave_write_stats". Also,
>write_stats sounds like a bad name to me (I know its from the
>documentation). But that could be a second patch.
>
>> @@ -462,6 +462,16 @@ def i2c_slave_read(self):
>         del data[ret:]
>         return (slave_addr, data.tostring())
> 
>+    def i2c_slave_set_response(self, data):
>+        """Prepare response to next read command.
>+
>+        Args:
>
>Just describe the data argument verbatim, just like in the other
>functions.
>
>Otherwise, the pull request looks good. Thank you.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontron/python-aardvark/pull/14#pullrequestreview-37282289

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by haggl** [comment]
Hmm, trying to run `python2 setup.py test` fails with:
```
AttributeError: 'module' object has no attribute 'test_aardvark'
```
Any ideas?

**Comment by mwalle** [comment]
are you trying to run the testsuite? try "python2 setup.py nostestes" or just "nosetests" in the toplevel directory.

**Comment by haggl** [comment]
I transformed `set_response` and `write_stats` to properties and added unit tests for those.


I also changed the docstring of `set_response` from Google-style to free-style. You should check if it actually arrives in the generated docs. This write-only property thing looks a bit hacky to me. If you have a better idea how to do this, please let me know.

**Comment by mwalle** [comment]
I guess you made the set_response a write only property because the underlying API doesn't provide a function to read it back. IMHO there is no reason that the Python API should do the same thing. You could provide both a getter and a setter. Simply remember the last set response, if there is a get without a prior set, return None. I know this falls short if the hardware is shared or a device is opened where a slave response is already set.

**Comment by haggl** [comment]
You are right. I did the same thing with the GPIO API as well.

**Comment by mwalle** [comment]
Thanks!

**Pull request merged**
